"""empty message

Revision ID: 99c7c3152c37
Revises: b9bef36e6ee4
Create Date: 2023-01-11 19:31:22.450061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c7c3152c37'
down_revision = 'b9bef36e6ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))
        batch_op.drop_column('imgage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgage', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
