"""empty message

Revision ID: b9bef36e6ee4
Revises: 
Create Date: 2023-01-11 18:28:21.061210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bef36e6ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ability', sa.String(length=50), nullable=False),
    sa.Column('baseExp', sa.Integer(), nullable=False),
    sa.Column('imgage', sa.String(), nullable=False),
    sa.Column('attackExp', sa.Integer(), nullable=False),
    sa.Column('hpExp', sa.Integer(), nullable=False),
    sa.Column('defenseExp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
