"""empty message

Revision ID: f5e66c989a72
Revises: 0d954cc87855
Create Date: 2023-01-17 14:21:10.205648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e66c989a72'
down_revision = '0d954cc87855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokeball',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ability', sa.String(length=50), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('sprite_url', sa.String(), nullable=False),
    sa.Column('attack_base', sa.Integer(), nullable=False),
    sa.Column('hp_base', sa.Integer(), nullable=False),
    sa.Column('defense_base', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokeball')
    # ### end Alembic commands ###
